### ISSUE TITLE
Fix weird scrolling behavior on pages where REPL is included

### ISSUE THREAD

**Issue by prakhar1989** [prakhar1989/gitbook-plugin-repl#4]

**Comment by prakhar1989** [comment]
Fixed in https://github.com/prakhar1989/gitbook-plugin-clojurescript/commit/8f7ef1f42c43652d1bd79f1a4e25e77efc1f5532. Thanks @vickychijwani :dancers:

**Comment by vickychijwani** [comment]
@prakhar1989 pair ~~dancing~~ debugging FTW!

**Comment by prakhar1989** [comment]
:grinning: :grinning: :grinning:
